{
  #set new name for each experiment, otherwise files will be overwritten
  'EXP_NAME' : '2021-11-19_ZZusingSH_TEST',
  'EVOLVER_IP' : '10.0.0.3',
  'EVOLVER_PORT' : 8081,
  # Vials that are in use
  'VIALS' : [8,9,10,11],


  ##### Identify pump calibration files, define initial values for temperature, stirring, volume, power settings

  'TEMP_INITIAL' : [30,30,30,30,30,30,30,30,30,30,30,30,30,30,30,30], #degrees C

  'STIR_INITIAL' : [9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9],

  'POWER_INITIAL' : [4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095,4095],

  'VOLUME' :  30, #mL, determined by vial cap straw length
  'PUMP_CAL_FILE' : 'pump_cal.txt', #tab delimited, mL/s with 16 influx pumps on first row, etc.
  'OPERATION_MODE' : 'morbidostat', # TURBIDOSTAT AND CHEMOSTAT FUNCTION HAS BEEN REMOVED FROM THIS VERSION
  # if using a different mode, name your function as the OPERATION_MODE variable

  'morbidostat' : {
    # Global paramemters for PID
    'VOLUME' : 28.0,                              # Volume assumed for dilution events (mL)
    'INITIAL_WAIT' : 1,                            # hours, time for initial growth
    'DILUTION_OD' : 0.4,                         # OD at which dilutions start occurring
    'MAX_OD' : 1.5,                                # High OD safeguard to prevent culture from leaving linear range
    'SUPER_OD' : 2.0,
    'DOUBLING_TIME' : 6.0,                         # User defined target doubling time
    ##'TARGET_GR' : math.log(2.0)/DOUBLING_TIME     # Calculated based off the user defined doubling time
    'STEPS_PER_HOUR' : 2,                          # User defined number of dilution events per hour. Volumes are adjusted accordingly
    ##'DILUTION_RATE' : float(VOLUME / DOUBLING_TIME) # mL / hour
    ##'VOLUME_PER_DILUTION' : float(DILUTION_RATE/ STEPS_PER_HOUR)
    ##'TIME_BETWEEN_DILUTIONS' : float(60/STEPS_PER_HOUR) #minutes
    ##'TIME_OUT' : VOLUME_PER_DILUTION + 3          # seconds to run pump for output

    # PID Parameters
    # Kp, Ki, Kd may need to be changed for different selections
    'Kp' :         [0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7,  0.7  ],
    'Ki' :         [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05 ],
    'Kd' :         [0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.2  ],
    'pid_offset' : [0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0  ],
  },

  'turbidostat' : {
    ##### USER DEFINED VARIABLES #####

    'stop_after_n_curves' : 'inf', #set to inf to never stop, or integer value to stop diluting after certain number of growth curves
    'OD_values_to_average' : 6,  # Number of values to calculate the OD average

    'lower_thresh' : [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], #to set all vials to the same value, creates 16-value list
    'upper_thresh' : [4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4], #to set all vials to the same value, creates 16-value list

    #Alternatively, use 16 value list to set different thresholds, use 9999 for vials not being used
    #lower_thresh : [0.2, 0.2, 0.3, 0.3, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999]
    #upper_thresh : [0.4, 0.4, 0.4, 0.4, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999, 9999]


    ##### END OF USER DEFINED VARIABLES #####


    ##### Turbidostat Settings #####
    #Tunable settings for overflow protection, pump scheduling etc. Unlikely to change between expts

    'time_out' : 5, #(sec) additional amount of time to run efflux pump
    'pump_wait' : 3, # (min) minimum amount of time to wait between pump events

    ##### End of Turbidostat Settings #####
  },

  'chemostat' : {
    ##### USER DEFINED VARIABLES #####
    'start_OD' : 0, # ~OD600, set to 0 to start chemostate dilutions at any positive OD
    'start_time' : 0, #hours, set 0 to start immediately
    # Note that script uses AND logic, so both start time and start OD must be surpassed

    'OD_values_to_average' : 6,  # Number of values to calculate the OD average

    'rate_config' : [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5],
    #UNITS of 1/hr, NOT mL/hr, rate : flowrate/volume, so dilution rate ~ growth rate, set to 0 for unused vials


    ##### END OF USER DEFINED VARIABLES #####


    ##### Chemostat Settings #####

    #Tunable settings for bolus, etc. Unlikely to change between expts
    'bolus' : 0.5, #mL, can be changed with great caution, 0.2 is absolute minimum

    ##### End of Chemostat Settings #####
  },
}
